AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - lib/templates/rails/**/*.rb
    - bin/*
    - views/**/*

Metrics/ModuleLength:
  Max: 120

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 220

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 40

# Missing top-level class documentation comment
Style/Documentation:
  Enabled: false

# Assignment Branch Condition size for %s is too high. [%.4g/%.4g]
Metrics/AbcSize:
  Max: 45

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 10

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/contact.rb'
